main/mysite/board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:postId>/', views.detail, name='detail'),
    path('answer/create/<int:postId>/', views.answer_create, name='answer_create'),
]

main/mysite/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='main.html'), name='logout'),
    path('register/', views.register, name='register'),
    path('change/', views.change, name='change'),
]

main/mysite/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('common.urls')),
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
    path('admin/', admin.site.urls),

    #path('common/', include('common.urls')),
]

main/mysite/board/models.py
from django.db import models


class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    writer = models.CharField(max_length=20)
    date = models.DateTimeField()

    def __str__(self):
        return self.title


class Answer(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField()
    writer = models.CharField(max_length=20)
    date = models.DateTimeField()

    def __str__(self):
        return self.title
# Create your models here.

main/mysite/common/models.py
from django.db import models


from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(primary_key=True, max_length=20)

# Create your models here.

main/mysite/common/forms.py
from django import forms
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("username", "email", "password")

main/mysite/board/views.py
from django.shortcuts import render


from .models import Post

def index(request):
    # 게시물 목록 출력
    postList = Post.objects.order_by('-date')
    context = {'postList': postList}
    return render(request, 'board/list.html', context)

def detail(request, postId):
    # 상세보기
    post = Post.objects.get(id=postId)
    context = {'post': post}
    return render(request, 'board/detail.html', context)

def answer_create(request, postId):
    # 답글 추가
    post = get_object_or_404(Post, pk=postId)
    post.answer_set.create(content=request.POST.get('content'), date=timezone.now())
    return redirect('board:detail', postId=postId)
#Create your views here.

main/mysite/common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.http import HttpResponse
from .models import Profile

def index(request):
    return render(request, 'main.html')

def register(request):
    if request.method == "POST":
        if request.POST["password1"] == request.POST["password2"]:
            user = User.objects.create_user(
                username=request.POST["username"],
                password=request.POST["password1"],
                email=request.POST["email"]
            )
            profile = Profile(
                user=user,
                name=request.POST["name"],
                # is_admin=request.POST.get('is_admin', '') == 'on'
            )
            profile.save()
            return render(request, 'common/register_done.html', {'user': user})
        else:
            return HttpResponse("Passwords do not match")
    else:
        return render(request, 'common/register.html')



def change(request):
    if request.method == "POST":
        profile = Profile.objects.get(user=request.user)
        profile.name = request.POST["name"]
        # profile.is_admin = request.POST.get('is_admin', '') == 'on'
        profile.save()
        return redirect('/')
    else:
        return render(request, 'common/change.html')

def logout(request):
    if request.method == 'POST':
        auth.logout(request)
        redirect('home')
    return render(request,'main.html')

# from django.contrib.auth import authenticate, login
# from django.shortcuts import render, redirect
# from .models import Profile
# from django.contrib.auth.models import User

# def index(request):
#     return render(request, 'main.html')

# def register(request):
#     if request.method == "POST":
#         if request.POST["password1"] == request.POST["password2"]:
#             user = User.objects.create_user(
#                 username=request.POST["username"],
#                 password=request.POST["password1"],
#                 email=request.POST["email"])
#             profile = Profile(
#                 user=user,
#                 name=request.POST["name"],
#                 is_admin=request.POST.get('is_admin', '') == 'on')
#             profile.save()
#             return redirect('/')
#     else:
#         return render(request, 'common/register.html')


# def change(request):
#     if request.method == "POST":
#         profile = Profile.objects.get(user=request.user)
#         profile.name = request.POST["name"]
#         profile.is_admin = request.POST.get('is_admin', '') == 'on'
#         profile.save()
#         return redirect('/')
#     else:
#         return render(request, 'common/change.html')

# #Create your views here.

main/mysite/templates/board/detail.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
<div class="container my-3">
    <h2 class="border-bottom py-2">{{ post.title }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ post.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">{{ post.date }}</div>
            </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">{{post.answer_set.count}}개의 답글이 있습니다.</h5>
    {% for answer in post.answer_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">{{ answer.date }}</div>
            </div>
        </div>
    </div>
    {% endfor %}
    <form action="{% url 'board:answer_create' post.id %}" method="post" class="my-3">
        {% csrf_token %}
        <div class="form-group">
            <textarea name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답글등록" class="btn btn-primary">
    </form>
</div>

main/mysite/templates/board/index.html
<html>
	<head>
		<title>자기소개</title>
	</head>
	<body>
		이름: {{r.name}}<br>
		나이: {{r.age}}<br>
		직업: {{r.job}}<br>
	</body>
</html>

main/mysite/templates/board/list.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
<div class="container my-3">
    <table class="table">
        <thead>
            <tr class="thead-dark">
                <th>번호</th><th>제목</th><th>작성일시</th><th>작성자</th>
            </tr>
        </thead>
        <tbody>
        {% if postList %}
        {% for post in postList %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td><a href="{% url 'board:detail' post.id %}">{{ post.title }}</a></td>
            <td>{{ post.date }}</td>
            <td>{{ post.writer }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr><td colspan="3">게시물이 없습니다.</td></tr>
        {% endif %}
        </tbody>
    </table>
</div>

main/mysite/templates/common/change.html
<form method="post" class="post-form" action="{% url 'common:change' %}">
  {% csrf_token %}
  <!-- Heading -->
  <h3 class="dark-grey-text text-center">
    <strong>프로필 변경</strong>
  </h3>
  <hr>
  <div class="md-form">
    <i class="fas fa-user prefix grey-text"></i>
    <input type="text" name="username" id="username" class="form-control" value="{{ request.user }}" readonly>
  </div>
  <div class="md-form">
    <i class="fas fa-envelope prefix grey-text"></i>
    <input type="email" name="email" id="email" class="form-control" value="{{ request.user.email }}" readonly>
  </div>                                        
  <div class="md-form">
    <i class="fas fa-signature prefix grey-text"></i>
    <input type="text" name="name" id="name" class="form-control" value="{{ request.user.profile.name }}">
  </div>                                   
  <div class="md-form custom-control custom-checkbox ml-4">
    <input type="checkbox" class="custom-control-input" name="is_admin" id="is_admin">
    <label class="custom-control-label" for="is_admin">관리자 여부</label>
  </div>                      
  <div class="text-center">
    <button class="btn btn-indigo">프로필 변경</button>
  </div>                   
  </form>

<script type="text/javascript">
    {% if request.user.profile.is_admin %}
        $("input:checkbox[id='is_admin']").attr("checked", true);
    {% else %}
        $("input:checkbox[id='is_admin']").attr("checked", false);
    {% endif %}
</script>

main/mysite/templates/common/register.html
{% include "header.html" %}

{% block content %}
{% endblock %}

{% load static %}

<body class="bg-primary">
  <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
  <br><br>

  <div class="container my-5 bg-white" style="width: 30%; border-radius:30px; box-shadow: 5px 5px 5px #000080;">
    <br><br>
    <form method="post" class="post-form" action="{% url 'common:register' %}">
      {% csrf_token %}
      <h3 class="dark-grey-text text-center"><strong>회원가입</strong></h3><br><br>
      
      <table class="table table-borderless">
        <tbody>
          <tr>
            <td><i class="fas fa-user prefix grey-text"></i></td>
            <td><input type="text" name="username" id="username" class="form-control" placeholder="아이디"></td>
            <td><i class="fas fa-user prefix grey-text"></i></td>

          </tr>
          <tr>
            <td><i class="fas fa-key prefix grey-text"></i></td>
            <td><input type="password" name="password1" id="password1" class="form-control" placeholder="비밀번호"></td>
          </tr>
          <tr>
            <td><i class="fas fa-key prefix grey-text"></i></td>
            <td><input type="password" name="password2" id="password2" class="form-control" placeholder="비밀번호 확인"></td>
          </tr>
          <tr>
            <td><i class="fas fa-envelope prefix grey-text"></i></td>
            <td><input type="email" name="email" id="email" class="form-control" placeholder="이메일"></td>
          </tr>
          <tr>
            <td><i class="fas fa-signature prefix grey-text"></i></td>
            <td><input type="text" name="name" id="name" class="form-control" placeholder="성명/회사명"></td>
          </tr>
        </tbody>
      </table><br><br>

      <div class="text-center">
        <button class="btn btn-indigo">회원가입</button><br><br>
      </div>                    
    </form>
  </div>
  <style>
    .btn-indigo:hover {
		color: #007BFF;
		text-decoration: underline;
    }
  </style>
</body>

main/mysite/templates/common/register_done.html
{% include "header.html" %} 
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
{% load static %}

  <body class="bg-primary">
  <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}"><br><br>
  <div class="container my-5 bg-white" style="width: 30%; border-radius:30px; box-shadow: 5px 5px 5px #000080;">
	<form method="post" class="post-form mx-auto form-group" action="{% url 'common:login' %}">
	  {% csrf_token %}<br>
	  <h3 class="dark-grey-text text-center"><br><br>
		<strong>회원가입이 완료되었습니다.</strong>
	  </h3>
	  <br><br>
	  <table class="table table-borderless">
		<tr>
        <td style="text-align: center;"><b>{{ user.profile.name }} 고객님</b></td>
		</tr>
		<tr>
		  <td></td>
		</tr>
	  </table>
	  <div class="text-center">
		<button class="btn btn-indigo" href="{% url 'common:login' %}">로그인</button>
		<br><br>	  </div>
	</form><br>
  </div>
  </body>
  <style>
    .btn-indigo:hover {
		color: #007BFF;
		text-decoration: underline;
    }
  </style>
</body>

main/mysite/templates/common/signup.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">

<div class="container my-3">
    <div class="row my-3">
        <div class="col-4">
            <h4>계정생성</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'common:login' %}">로그인 하세요.</a></span>
        </div>
    </div>
    <form method="post" action="{% url 'common:signup' %}" class="post-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>

main/mysite/templates/error.html
<h1>잘못된 접근입니다.</h1>

main/mysite/templates/header.html
<!-- Header 부분에 삽입될 내용 -->
<nav class="navbar navbar-expand-lg navbar-light bg-white">
  <div class="container">
    <a class="navbar-brand" href="http://www.metanettplatform.co.kr/"><img src="https://postfiles.pstatic.net/MjAyMzA0MTZfMTk3/MDAxNjgxNTcyNDg5OTc5.JDd0reszBufPa7rVWCav2TygRBXIKvjeSwFhDXVIqOog.z__SQqnrdNCKVy5-rik5hv88NW4X2rsnL9X4iSBJx0og.JPEG.hyeran0920/587b148e81bebcc8cb450b8de519884c_1538367090_56.jpeg?type=w773"width="120"></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto">      
        <li class="nav-item">
      </li>
	<li class="nav-item">
          <a class="nav-link active text-uppercase" aria-current="page" href="/">Home</a>
        </li>

        {% if user.is_authenticated %}
      	<li class="nav-item">
        <a href="{% url 'common:logout' %}" class="nav-link active">로그아웃</a>
        </li>
	<li class="nav-item">
    <b class="nav-link text-primary" style="font-weight: bold;">{{ user.profile.name }} 고객님</b>
  </li>            
  {% else %}
  <li class="nav-item">
    <a class="nav-link active" href="{% url 'common:login' %}">&nbsp;&nbsp;&nbsp;로그인</a>
  </li>
<li class="nav-item">
    <a class="nav-link active" href="{% url 'common:register' %}">&nbsp;&nbsp;&nbsp;회원가입</a>
  </li>
  {% endif%}
      </ul>

      
<!--      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
          </form> -->
    </div>
  </div>
</nav>
<!-- ------------------------------ -->

main/mysite/templates/login.html
{% include "header.html" %} 
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
{% load static %}

  <body class="bg-primary">
  <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}"><br><br>
  <div class="container my-5 bg-white" style="width: 30%; border-radius:30px; box-shadow: 5px 5px 5px #000080;">
	<form method="post" class="post-form mx-auto form-group" action="{% url 'common:login' %}">
	  {% csrf_token %}<br>
	  <h3 class="dark-grey-text text-center">
		<strong>로그인</strong>
	  </h3>
	  <br><br>
	  <table class="table table-borderless">
		<tr>
		  <td><input type="text" name="username" id="username" class="form-control" placeholder="아이디"></td>
		</tr>
		<tr>
		  <td><input type="password" name="password" id="password" class="form-control" placeholder="비밀번호"></td>
		</tr>
	  </table>
	  <div class="text-center">
		<button class="btn btn-indigo" href="/">로그인</button>
		<br><br>
		<a href="{% url 'common:register' %}">회원이 아닌가요? 회원가입</a>
	  </div>
	</form><br>
  </div>
  </body>
  <style>
    .btn-indigo:hover {
		color: #007BFF;
		text-decoration: underline;
    }
  </style>
</body>

main/mysite/templates/main.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <title>Main Page</title>
</head>
<header>
  {% include "header.html" %} 
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
</header>
<body>
  <div class="container-fluid" id="intro-section">
    <div class="intro-text">
      <h1>MetaNet Internship Project</h1><br>
      <h3>CI/CD환경을 구축하기 위한  kubernetes활용 및  terraform으로 MSA구조 인프라 설계</h3>
    </div>
  </div>
  
  
  <style>
    .container-fluid {
      height: 100vh;
      position: relative;
    }
  
    .intro-text {
      position: absolute;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%);
      text-align: center;
      z-index: 3;
    }
  
    #intro-section {
      background-color: #999;
      transition: background-color 0.5s ease;
    }
  
    #intro-section.bg-color {
      background-color: #fff;
    }
  </style>
  
  
  <script>
    $(document).ready(function(){
      $(window).scroll(function() {
        var scrollTop = $(this).scrollTop();
        var introSectionHeight = $('#intro-section').outerHeight();
        // If user has scrolled past intro section
        if (scrollTop > (introSectionHeight - $(window).height())) {
          $('#intro-section').addClass('bg-color');
        } else {
          $('#intro-section').removeClass('bg-color');
        }
      });
    });
  </script>
  


<div class="container mt-5">
  <h1>팀원 소개</h1><br>
  <div class="row">
    <div class="col-sm-3">
      <img src="https://cdn-icons-png.flaticon.com/512/1372/1372643.png" width="100">
      <h3>김성현</h3>
      <b>조장 CI/CD </b>
      <p>젠킨스를 이용하여 Docker 파일 확인과 배포를 담당</p>
    </div>
    <div class="col-sm-3">
      <img src="https://cdn-icons-png.flaticon.com/512/4439/4439950.png" width="100">
      <h3>서유진</h3>
      <b>Django</b>
      <p>Django를 이용하여 웹사이트 구축</p>
    </div>
    <div class="col-sm-3">
      <img src="https://cdn-icons-png.flaticon.com/512/4439/4439950.png" width="100">
      <h3>이솔</h3>
      <b>Log</b>
      <p>Log파일을 추출하여 이상 접속 차단</p>
    </div>
    <div class="col-sm-3">
      <img src="https://cdn-icons-png.flaticon.com/512/1372/1372643.png" width="100">

      <h3>조민기</h3>
      <b>Terraform</b>
      <p>Terraform을 이용하여 Infra 구축</p>
    </div>
  </div>
</div>
<br><br><br>

</body>
</html>